name: CI Pipeline


on:
  push:
    branches:["main","feature/*"]
  pull request:
    branches:["main"]

  jobs:
    build:
      runs-on: ubuntu-latest

  steps:
    - name: Checkout do c√≥digo
      uses: action/checkout@v4

    - name: SetupPython
      uses: actions/setup-python@v5
      with:
        python-version:"3.11"

    - name: Verificar sintaxe
      run: python -m compileall
  
  
